### ISSUE TITLE
Security tracking issue

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wapm-cli#115]
This is a tracking issue for improving the security of wapm.  Feedback welcome!

We should aim for at least tier 2 with the less intrusive parts of tier 3 from https://github.com/OWASP/packman#tiers-and-controls

### Tier 2
- [ ] Strong Authentication (verify that this is the case)
- [ ] MFA To Push Artifacts
  - [ ] Add 2fa
  - [ ] integrate it into wapm-cli
- [ ] Security Contacts 
- [ ] Packages Can Notify of Security Issues 
  - [ ] design this system
- [ ] Code package tied to source code (ambiguous, relevant?)
- [ ] Prevents Credential from Being Published
  - [ ] prevent private key from being published
     - [ ] packaging
     - [ ] key registration
  - [ ] protect password?
     - [ ] design this (scanning through all data is harder if salted + hashed, but we shouldn't store the password directly either)
- [ ] Update notifications
  - [ ] wapm itself
  - [ ] packages too (design this system)
